import React from 'react';
import './BlogOverviewPage.css'

const BlogOverviewPage = () => {
    return (
        <div className='blog-overview-page' >
            <h1 className='blog-title'>Way to go Precisio</h1>
            <p className='blog-content'>
            Bharat Vishal Rajan
            <br /><br />
            It was 2 pm on a hot Wednesday afternoon, when almost all the team members of Precisio were going zany over the skid pad test. The reason behind this, being that our go-kart wasn’t turning to the right properly because of the under steer. This problem , we thought arose because of the improper alignment of our tie rod. Just before the skid pad test, we were all praying to our dear gods to cast upon us a ray of light of hope for us to clear this test. And everyone were relying on our second driver, Mukesh to pass this test. It was time. I being one of the pits-man pushed up the kart to the start of the eight-shaped lap.
            <br/><br/>
            One! Two! Three! And the whistle was blown, our driver revved up his engine at the low gears to attain the torque and the traction to ride along the pathway without skidding or deviating from it. Mukesh had to take two rounds in the lower portion of the eight, turning towards the left continuously and then had to take another two rounds towards the right. He cleared the first two rounds with ease. But as the kart moved towards to take the right turn of the eight. The kart skid and it hit a cone shaped barricade at the border, and another one too. This led to an extra 4 second penalty because of fouling. Thus the first attempt didn’t prove to be so good.
            Then came the second attempt. This time Mukesh was going for it with a vengeance, to compensate for the last try. And the whistle blew, and he sped as fast as he could, still having the grip, and not letting the kart skid. While taking the right turn , he somehow manoeuvred without skidding and finished it off with a decent above average score of 44.25 seconds. This was considered to be an achievement by us, knowing the condition of our kart. But still, Mukesh wasn’t satisfied. He was waiting for another chance in some other event to prove himself.
            <br/><br/>
            Then came the autocross event, which involved driving the go kart through a series of cone-barricades in a zigzag manner. At the end of the track, the driver was supposed to take a deep left turn without going away from the set limit, else a penalty of 20 seconds would be imposed. This event gave us even more chills than the skid pad because, it involved a lot of twists and turns which were deeper than the latter. Our first driver Saravana suggested that Mukesh drive the kart for autocross as he had the ability to save a few seconds while driving. Initially the rules were all stupid, where the distance between successive cones decreased gradually from 5 metres to 4 metres towards the end. This proved to be an impossible task for any driver to clear the event without hitting a few cones. And hence the next day, the rules were slightly altered to make the track a little feasible.
            <br/><br/>
            Next day, 9 a.m. a cool and breezy morning, we lined up our kart for the autocross event. Mukesh was all geared up and determined to pull this through as good as he could. The rules were dictated once again by the official. And Mukesh just put up his thumb, indicating he was ready. The official signalled the start and up revved our engine. A good start and he continued. He hit a few cones, but still he finished it off with a good time of 36 seconds including the four penalties. He was determined for the second attempt. And we lined up the kart at the start. And the whistle blew! And what a wonderful sight we had! Our kart was flying. Mukesh was manoeuvring the kart so well. He raced to the end of the track and he made the almost impossible U-turn seem so simple. We were looking at him in awe, jaws dropped. And he finished the autocross with an incredible time of 29.15 seconds including a single penalty for hitting a cone. This was the second best time in the whole of the event. And he did it! He tamed our beast. Everyone came rushing to him shouting and screaming praises of joy and wonder. Saravana, a guy of simple and calm emotions, was jumping now and screaming the hell out. We were overwhelmed.
            <br/><br/>
            After this event, there was the final endurance test which involved going around the whole 2.2 kilometres of the race track for three laps. This was to test the lap time and the fuel economy of the vehicle. Our kart finished this with a good time of 7.02 minutes. At the end of the day after a lot of ups and downs, the results were announced. ‘The best driver award goes to Mukesh from team Precisio’. And that was the moment of his life, for Mukesh, he thanked his stars as he got the award. And almost immediately, the officials announced another prize for the best endurance kart, which was bagged by us too! Oh what a day it was! Everything seemed to me in slow motion, the announcement of the results, us getting the prizes and my fellow mates jumping with joy and it was all so magical. Yes, we, team PRECISIO, who were the underdogs from SSNCE now proved to be one of the top teams in the national go kart championship. Hip hip hurray! PRECISIO for the win!
            <br/><br/>
            P.S.: None of this could have been possible without the two main seeds who were like the chassis of the kart, Saravana, our first driver and founder of PRECISIO and Prasanna our captain cool. You both deserve the win more than anyone else in our group!
            </p>
        </div>
    )
}

export default BlogOverviewPage;